### ISSUE TITLE
Can't download error

### ISSUE THREAD

**Issue by zbychol** [Dniel97/orpheusdl-idagio#1]
When I try to download albums I often can't:

Downloading album Exclusive: Wiener Philharmoniker, Christian Thielemann, Dieter Flury (exclusive-wiener-philharmoniker-christian-thielemann-dieter-flury) ===
        Artist: Johannes Brahms (61368)
        Year: 2018
        Number of tracks: 14
        Service: Idagio
        Downloading album cover

        Track 1/14
        === Downloading track Akademische Festouvertüre (Academic Festival Overture) op. 80 (18730144) ===
                Artists: Christian Thielemann, Wiener Philharmoniker (61368)
                Release year: 2017
                Codec: FLAC, bitrate: 1411kbps, bit depth: 16bit, sample rate: 44.1kHz

                Downloading track file
                100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.0M/48.0M [00:01<00:00, 42.5MB/s]
                Downloading artwork
                Retrieving credits
                Tagging file
        === Track 18730144 downloaded ===

        Track 2/14
        === Downloading track Flûte en suite for Flute and Orchestra Groups (2011) (18730072) ===
                Artists: Christian Thielemann, Dieter Flury, Wiener Philharmoniker (66579)
                Release year: 2017
                Codec: FLAC, bitrate: 1411kbps, bit depth: 16bit, sample rate: 44.1kHz

                Downloading track file
                100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14.3M/14.3M [00:00<00:00, 44.1MB/s]
                Downloading artwork
                Retrieving credits
Traceback (most recent call last):
  File "C:\Users\...OrpheusDL-Idagio\orpheus.py", line 225, in <module>
    main()
  File "C:\Users\...OrpheusDL-Idagio\orpheus.py", line 220, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\...OrpheusDL-Idagio\orpheus\core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "C:\Users\...OrpheusDL-Idagio\orpheus\music_downloader.py", line 242, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "C:\Users\...OrpheusDL-Idagio\orpheus\music_downloader.py", line 536, in download_track
    credits_list = self.service.get_track_credits(track_id, **track_info.credits_extra_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...OrpheusDL-Idagio\modules\idagio\interface.py", line 333, in get_track_credits
    credits_dict[soloist.get('instrument').get('title')].append(credits_dict[soloist.get('person').get('name')])
                                                                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Dieter Flury'

How to repair it?

**Comment by ghost** [comment]
@Dniel97 my apologies for tagging you, but.. no publicly set means of communication.

Was merely wondering if this is still functioning? (similar projects no longer do)

Asking before i pay to subscribe to Idagio again :)

**Comment by OrfiDev** [comment]
He probably hasn't touched this service since he made this module so I wouldn't bet on it

**Comment by ghost** [comment]
Well, anyone similarly inclined could comment here in the future.
Must be someone with an active subscription around willing to test it.. fingers crossed anyway :)

**Comment by zbychol** [comment]
No, it isn't working.

**Comment by ghost** [comment]
Really appreciate it @zbychol 
At least we know.

Now if only someone could update it.. :)
